/*
 *  The ManaPlus Client
 *  Copyright (C) 2017-2018  The ManaPlus Developers
 *
 *  This file is part of The ManaPlus Client.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#define SERVERPERMISSION_VOID

// Hercules permissions
serverpermissionFirst(can_trade)
serverpermission(can_party)
serverpermission(all_skill)
serverpermission(all_equipment)
serverpermission(skill_unconditional)
serverpermission(join_chat)
serverpermission(kick_chat)
serverpermission(hide_session)
serverpermission(who_display_aid)
serverpermission(hack_info)
serverpermission(any_warp)
serverpermission(view_hpmeter)
serverpermission(view_equipment)
serverpermission(use_check)
serverpermission(use_changemaptype)
serverpermission(all_commands)
serverpermission(receive_requests)
serverpermission(show_bossmobs)
serverpermission(disable_pvm)
serverpermission(disable_pvp)
serverpermission(disable_commands_when_dead)
serverpermission(hchsys_admin)
serverpermission(can_trade_bound)
serverpermission(disable_pickup)
serverpermission(disable_store)
serverpermission(disable_exp)
serverpermission(disable_skill_usage)

// Evol permissions
serverpermission(send_gm)
serverpermission(show_client_version)
