.job-push: &job-push
  artifacts:
    paths:
    - logs
    when: always
    expire_in: 3 week
  dependencies: []

.job-always: &job-always
  artifacts:
    paths:
    - logs
    when: always
    expire_in: 3 week
  dependencies: []

gcc-4.4:
  stage: build
  script:
  - ./tools/ci/jobs/gcc44.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: ubuntu:trusty
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.4 g++-4.4 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker

gcc-4.1_sdl1:
  stage: build
  script:
  - ./tools/ci/jobs/gcc41.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: registry.gitlab.com/manaplus/images:gentoo_gcc41_sdl1
  <<: *job-push
  variables:
    PMUPDATE: "echo"
    PMINSTALL: "echo"
    NEWCC: gcc-4.1.2
    NEWCXX: g++-4.1.2
  tags:
    - docker

gcc-4.1_sdl2:
  stage: build
  script:
  - ./tools/ci/jobs/gcc41.sh --with-sdl2
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: registry.gitlab.com/manaplus/images:gentoo_gcc41_sdl2
  <<: *job-push
  variables:
    PMUPDATE: "echo"
    PMINSTALL: "echo"
    NEWCC: gcc-4.1.2
    NEWCXX: g++-4.1.2
  tags:
    - docker

gcc-4.3_sdl1:
  stage: build
  script:
  - ./tools/ci/jobs/gcc43.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: registry.gitlab.com/manaplus/images:gentoo_gcc43_sdl1
  <<: *job-push
  variables:
    PMUPDATE: "echo"
    PMINSTALL: "echo"
    NEWCC: gcc-4.3.6
    NEWCXX: g++-4.3.6
  tags:
    - docker

gcc-4.3_sdl2:
  stage: build
  script:
  - ./tools/ci/jobs/gcc43.sh --with-sdl2
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: registry.gitlab.com/manaplus/images:gentoo_gcc43_sdl2
  <<: *job-push
  variables:
    PMUPDATE: "echo"
    PMINSTALL: "echo"
    NEWCC: gcc-4.3.6
    NEWCXX: g++-4.3.6
  tags:
    - docker

gcc-4.4_i386:
  stage: build
  script:
  - ./tools/ci/jobs/gcc44.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: i386/ubuntu:trusty
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.4 g++-4.4 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker

gcc-4.5:
  stage: build
  script:
  - ./tools/ci/jobs/gcc45.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: ubuntu:12.04
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.5 g++-4.5 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker

gcc-4.6:
  stage: build
  script:
  - ./tools/ci/jobs/gcc46.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: ubuntu:trusty
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.6 g++-4.6 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker

gcc-4.6_i386:
  stage: build
  script:
  - ./tools/ci/jobs/gcc46.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: i386/ubuntu:trusty
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.6 g++-4.6 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker

gcc-4.7:
  stage: build
  script:
  - ./tools/ci/jobs/gcc47.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  - ./tools/ci/jobs/gcc47_c++11.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: ubuntu:trusty
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.7 g++-4.7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker

gcc-4.7_i386:
  stage: build
  script:
  - ./tools/ci/jobs/gcc47.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: i386/ubuntu:trusty
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.7 g++-4.7 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker

gcc-4.8:
  stage: build
  script:
  - ./tools/ci/jobs/gcc48.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  - ./tools/ci/jobs/gcc48_c++11.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: debian:jessie
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.8 g++-4.8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps

gcc-4.8_i386:
  stage: build
  script:
  - ./tools/ci/jobs/gcc48.sh
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: i386/debian:jessie
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.8 g++-4.8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker

gcc-4.8_sdl2:
  stage: build
  script:
  - ./tools/ci/jobs/gcc48.sh --with-sdl2
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: debian:jessie
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.8 g++-4.8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              gdb valgrind netcat-openbsd procps

gcc-4.8_sdl2_i386:
  stage: build
  script:
  - ./tools/ci/jobs/gcc48.sh --with-sdl2
  - ./tools/ci/scripts/runtests.sh
  - ./tools/ci/scripts/rundyecmd.sh
  image: i386/debian:jessie
  <<: *job-push
  variables:
    PACKAGES: git gcc-4.8 g++-4.8 
              make autoconf automake autopoint gettext 
              libxml2-dev libcurl4-gnutls-dev libpng-dev 
              libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev
              gdb valgrind netcat-openbsd procps
  tags:
    - docker
