
jobs:
- job: gcc7
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      export SDL1="libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev"
      export SDL2="libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev"
      export LIBS_PACKAGES="make autoconf automake autopoint gettext libxml2-dev libcurl4-gnutls-dev libpng-dev"
      export IMAGE=debian:unstable
      export COMMAND="./tools/ci/jobs/gcc7.sh --enable-werror"
      export PACKAGES="gcc-7 g++-7 ${LIBS_PACKAGES} ${SDL1} valgrind"
      ./tools/ci/scripts/docker_run.sh
- job: gcc7_sdl2_tests
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: |
      export SDL1="libsdl-gfx1.2-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-ttf2.0-dev"
      export SDL2="libsdl2-dev libsdl2-gfx-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-net-dev libsdl2-ttf-dev"
      export LIBS_PACKAGES="make autoconf automake autopoint gettext libxml2-dev libcurl4-gnutls-dev libpng-dev"
      export IMAGE=debian:unstable
      export COMMAND="./tools/ci/jobs/gcc7_tests.sh --without-dyecmd --without-manaplusgame --with-sdl2"
      export PACKAGES="gcc-7 g++-7 ${LIBS_PACKAGES} ${SDL2} valgrind"
      ./tools/ci/scripts/docker_run.sh
- job: macos10_13
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - script: |
      cd packaging/OSX || exit 1
      ./gethttps.sh || exit 1
      cd ../../Xcode || exit 1
      ./build.sh || exit 1
      ./pack.sh || exit 1
