#!/bin/sh

#may be
#-Wshadow -Waggregate-return -Winline 

#for feature
#-Wstrict-overflow=4 -Wfloat-equal
#-Wunsafe-loop-optimizations
#-Wnon-virtual-dtor
#-Woverloaded-virtual
#-Wformat=2
#-Wswitch-enum
#-Werror 

#for better code
# -Weffc++

#from time to time fix: -Wold-style-cast -Wconversion -Wswitch-enum -Waggregate-return
#from time to time fix: -Winline
#need fix: -Wsuggest-attribute=pure -Wsuggest-attribute=const
#need fix: -Wstrict-overflow=5 -fstrict-overflow
#need fix: -Wstrict-aliasing=3
#need fix: -Wdouble-promotion
#need fix: -Wfloat-equal
#need fix: -Wunsafe-loop-optimizations
#need fix: -Wpadded
#prof -pg

dir=`pwd`

export CC=gcc-4.6
export CXX=g++-4.6

export LANG=C

export CXXFLAGS="-Wvariadic-macros -Wvla -Wredundant-decls \
-Wpacked-bitfield-compat -Wcast-qual -Wtrampolines \
-Wsuggest-attribute=noreturn -Wunused -Wstrict-aliasing=2 \
-fstrict-aliasing -Wunreachable-code -Wabi -Wdisabled-optimization \
-Wvolatile-register-var -Winvalid-pch -Wredundant-decls \
-Wnormalized=nfkc -Wmissing-format-attribute -Wmissing-noreturn \
-Wswitch-default -Wsign-promo -Waddress -Wmissing-declarations \
-Wctor-dtor-privacy -Wstrict-null-sentinel -Wlogical-op \
-Wcast-align -Wcast-qual -Wpointer-arith -Wundef \
-Wmissing-include-dirs -Winit-self -pedantic -Wall -ggdb3 -O2 -pipe \
-Wpacked -Wextra -Wstrict-overflow=1 -Wunknown-pragmas -Wwrite-strings \
-Wstack-protector"

autoreconf -i
./configure --prefix=$dir/run \
--datadir=$dir/run/share/games \
--bindir=$dir/run/bin \
--mandir=$dir/run/share/man

cd po
#make -j5 update-po 2>../make1.log
make -j5 update-gmo 2>../make1.log
cd ..
make -j5 2>make2.log

