#!/bin/bash

dir=`pwd`

cd packaging/windows
./make-translations.sh
makensis -DDLLDIR=$dir/../mana_win/libs/dll/ \
    -DPRODUCT_VERSION="4144-1.0.12.26" \
    -DEXESUFFIX=/src \
    -DUPX=true \
    setup.nsi

