#!/bin/bash

dir=`pwd`

cd packaging/windows
./make-translations.sh
makensis -DDLLDIR=$dir/../mana_win/libs/dll/ \
    -DPRODUCT_VERSION="1.1.7.10" \
    -DEXESUFFIX=/src \
    -DUPX=true \
    setup.nsi

