.TH "ManaPlusTest" "6"
.SH "NAME"
manaplustest \- ManaPlusTest: test tool for manaplus
.SH "SYNOPSIS"
\fBmanaplustest\fR
.SH "DESCRIPTION"
Graphics and configuration tool for manaplus.

.SH "AUTHOR"
This manual page was written by Andrei Karas <akaras@inbox.ru>
for the ManaPlus project.
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU General Public License, version 2 or any
later version published by the Free Software Foundation.
